# ===============================
# Application
# ===============================
spring.application.name=url-shortener

# ===============================
# MySQL Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/urldb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Karthik@0306
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 Console (Development Only)
# ===============================
spring.h2.console.enabled=true

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.karthik.urlshortener=DEBUG

# ===============================
# Server
# ===============================
server.port=8080