package com.karthik.urlshortener.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "url")
public class UrlEntity {

    private Long id;

    @Column(name = "full_url", nullable = false, length = 2048)
    private String fullUrl;

    @Column(name = "short_url", nullable = false, unique = true, length = 50)
    private String shortUrl;

    public UrlEntity() {
    }

    public UrlEntity(Long id, String fullUrl, String shortUrl) {
        this.id = id;
        this.fullUrl = fullUrl;
        this.shortUrl = shortUrl;
    }

    public UrlEntity(String fullUrl) {
        this.fullUrl = fullUrl;
    }

    public UrlEntity(String fullUrl, String shortUrl) {
        this.fullUrl = fullUrl;
        this.shortUrl = shortUrl;
    }

    /**
     * Returns the unique identifier generated by the database.
     *
     * @return database-generated ID
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }

    /**
     * Sets the database-generated ID.
     *
     * @param id URL identifier
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the original URL.
     *
     * @return full URL
     */
    public String getFullUrl() {
        return fullUrl;
    }

    /**
     * Sets the original URL.
     *
     * @param fullUrl original URL
     */
    public void setFullUrl(String fullUrl) {
        this.fullUrl = fullUrl;
    }

    /**
     * Returns the shortened URL code.
     *
     * @return short URL code
     */
    public String getShortUrl() {
        return shortUrl;
    }

    /**
     * Sets the shortened URL code.
     *
     * @param shortUrl short URL code
     */
    public void setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl;
    }

    @Override
    public String toString() {
        return "UrlEntity{" +
                "id=" + id +
                ", fullUrl='" + fullUrl + '\'' +
                ", shortUrl='" + shortUrl + '\'' +
                '}';
    }
}